### ISSUE TITLE
 Didn't find class .Main Application" on path:

### ISSUE THREAD

**Issue by luizcarlospedrosogomes** [orYoffe/create-react-native-web-app#42]
![image](https://user-images.githubusercontent.com/9791364/56653895-229dae80-6665-11e9-8188-7036635d2685.png)

OS; windows 10 x 64
react-native-cli: 2.0.1
react-native: 0.55.4
emulador: android studio

error:
2019-04-24 08:06:36.515 23312-23312/com.myappup E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.myappup, PID: 23312
    java.lang.RuntimeException: Unable to instantiate application com.myappup.MainApplication: java.lang.ClassNotFoundException: Didn't find class "com.myappup.MainApplication" on path: DexPathList[[zip file "/data/app/com.myappup-WeBzEpEmX8pRRzvTQfjTBA==/base.apk"],nativeLibraryDirectories=[/data/app/com.myappup-WeBzEpEmX8pRRzvTQfjTBA==/lib/arm, /data/app/com.myappup-WeBzEpEmX8pRRzvTQfjTBA==/base.apk!/lib/armeabi-v7a, /system/lib, /vendor/lib]]
        at android.app.LoadedApk.makeApplication(LoadedApk.java:1015)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6072)
        at android.app.ActivityThread.-wrap1(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1791)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:7000)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:441)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1408)
     Caused by: java.lang.ClassNotFoundException: Didn't find class "com.myappup.MainApplication" on path: DexPathList[[zip file "/data/app/com.myappup-WeBzEpEmX8pRRzvTQfjTBA==/base.apk"],nativeLibraryDirectories=[/data/app/com.myappup-WeBzEpEmX8pRRzvTQfjTBA==/lib/arm, /data/app/com.myappup-WeBzEpEmX8pRRzvTQfjTBA==/base.apk!/lib/armeabi-v7a, /system/lib, /vendor/lib]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:125)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        at android.app.Instrumentation.newApplication(Instrumentation.java:1095)
        at android.app.LoadedApk.makeApplication(LoadedApk.java:1009)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6072) 
        at android.app.ActivityThread.-wrap1(Unknown Source:0) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1791) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:164) 
        at android.app.ActivityThread.main(ActivityThread.java:7000) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:441) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1408)

**Comment by orYoffe** [comment]
@luizcarlospedrosogomes could you please write the steps to reproduce?
did you run npm start and npm run android?

**Comment by luizcarlospedrosogomes** [comment]
@orYoffe npm run android

**Comment by luizcarlospedrosogomes** [comment]
https://github.com/orYoffe/create-react-native-web-app/issues/43
