### ISSUE TITLE
Android app crash with error 'com.facebook.jni.CppException : Can't find variable: setTimeout' android 64 bit with React native 0.59.10

### ISSUE THREAD

**Issue by sunildate05** [orYoffe/create-react-native-web-app#62]
**App crashing on launch with setTimeOut error**

I have created project using create-react-native-web command & upgraded 0.55.x to 0.59.10 for android 64 bit support using [https://react-native-community.github.io/upgrade-helper/?from=0.55.3&to=0.59.10]()

We are facing below error on launching app crash -

Error in details -

 com.facebook.jni.CppException: Can't find variable: setTimeout
    
    index.android.bundle:206:7357
    h@index.android.bundle:2:1670
    index.android.bundle:205:53
    h@index.android.bundle:2:1670
    index.android.bundle:204:92
    h@index.android.bundle:2:1670
    index.android.bundle:13:2046
    h@index.android.bundle:2:1670
    index.android.bundle:11:46
    h@index.android.bundle:2:1670
    d@index.android.bundle:2:868
    global code@index.android.bundle:304:4
        at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
        at android.os.Handler.handleCallback(Handler.java:739)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:29)
        at android.os.Looper.loop(Looper.java:148)
        at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:232)

Can you please help us?

**Comment by orYoffe** [comment]
no idea, I would create an issue on react-native project instead if i were you. Hope it works out or that you'll find a solution with google. I didn't do this myself yet
