### ISSUE TITLE
Error: https://registry.yarnpkg.com/react-native-template-react-native-template-react-native-web: Not found

### ISSUE THREAD

**Issue by freekingg** [orYoffe/create-react-native-web-app#93]
run
```
npx crnwa myApp
```

`

Yarn version: 
  1.22.10

Node version: 
  14.15.1

Platform: 
  darwin x64

Trace: 
  Error: https://registry.yarnpkg.com/react-native-template-react-native-template-react-native-web: Not found
      at Request.params.callback [as _callback] (/usr/local/Cellar/yarn/1.22.10/libexec/lib/cli.js:66988:18)
      at Request.self.callback (/usr/local/Cellar/yarn/1.22.10/libexec/lib/cli.js:140749:22)
      at Request.emit (events.js:315:20)
      at Request.<anonymous> (/usr/local/Cellar/yarn/1.22.10/libexec/lib/cli.js:141721:10)
      at Request.emit (events.js:315:20)
      at IncomingMessage.<anonymous> (/usr/local/Cellar/yarn/1.22.10/libexec/lib/cli.js:141643:12)
      at Object.onceWrapper (events.js:421:28)
      at IncomingMessage.emit (events.js:327:22)
      at endReadableNT (_stream_readable.js:1327:12)
      at processTicksAndRejections (internal/process/task_queues.js:80:21)

`

**Comment by orYoffe** [comment]
@freekingg still having the issue? could you give a bit more details?
like running `npx crnwa --version` to make sure you have the latest version.
most common issue with `npx` i saw that people had, was having an earlier version installed globally

**Comment by orYoffe** [comment]
Closing for lack of a reply
